### ISSUE TITLE
Demo 01

### ISSUE THREAD

**Issue by lhbdhr** [peach-djf/WebStudy#1]
input 默认提示内容 用 placeholder更好一些

**Comment by df13954** [comment]
大佬居然看到了我的demo，震惊~~，默认提示内容input中，以前的时候不是用placeholder，所以需要做出那个鼠标，或者删除之后恢复的效果需要自己写。刚刚查询了placeholder，是h5的特效，估计是简化了那个效果的流程。让我们不用写得这么复杂。个人估计，其实内部的实现，也是和我们手写的差不多吧，只是他们把代码抽离，做成了placeholder。小白的想法，大佬别笑

**Comment by lhbdhr** [comment]
并不是大佬  只是学的早了一点  学了大半年  差不多到了找工作的阶段 
推荐个教程吧  网易初级前端工程师微专业 的课程，个人感觉很好。
资源可以轻易搜到

**Comment by lhbdhr** [comment]
可以加个QQ呀 新手还是可以指导一下的。
教的过程也是复习的过程。
QQ 169689909
有问题 可以甩过来
